import type { IconId } from "../../data/skills";

const palette: Record<string, string> = {
  "#": "#3d2514", w: "#fdfbf7", g: "#52b788", G: "#2d6a4f", r: "#e63946", y: "#f4d35e",
  b: "#4ea8de", t: "#dda15e", o: "#bc6c25", k: "#152e22", p: "#9d4edd", s: "#8d99ae",
};

const maps: Record<IconId | "mushroom", string[]> = {
  frontend: [
    "............",
    ".##########.",
    ".#tttttttt#.",
    ".##########.",
    ".#wwwwwwww#.",
    ".#wbbbwwww#.",
    ".#wbbbwggw#.",
    ".#wwwwwggw#.",
    ".#wyyyywww#.",
    ".#wwwwwwww#.",
    ".##########.",
    "............",
  ],
  backend: [
    "............",
    "..########..",
    "..#sssssr#..",
    "..########..",
    "..#sssssg#..",
    "..########..",
    "..#sssssg#..",
    "..########..",
    "....#..#....",
    "..########..",
    "............",
    "............",
  ],
  devops: [
    "............",
    "....####....",
    "..##wwww##..",
    ".#wwwwwwww#.",
    ".#wwwwwwwww#",
    ".#wwwwwwwww#",
    "..#########.",
    "....#gy#....",
    "....#gy#....",
    "....####....",
    "............",
    "............",
  ],
  satchel: [
    "............",
    "....####....",
    "...#t..t#...",
    "..########..",
    ".#tttttttt#.",
    ".#ttoooott#.",
    ".#ttoyyott#.",
    ".#ttoooott#.",
    ".#tttttttt#.",
    ".##########.",
    "............",
    "............",
  ],
  scroll: [
    "............",
    ".##########.",
    ".#yyyyyyyy#.",
    ".#y######y#.",
    ".#yyyyyyyy#.",
    ".#y######y#.",
    ".#yyyyyyyy#.",
    ".#y####yyy#.",
    ".#yyyyyyyy#.",
    ".##########.",
    "............",
    "............",
  ],
  me: [
    "............",
    "...######...",
    "..#kkkkkk#..",
    ".#kwwwwwwk#.",
    ".#wwwwwwww#.",
    ".#w#ww#www#.",
    ".#wwwwwwww#.",
    ".#ww####ww#.",
    "..#wwwwww#..",
    "...######...",
    "............",
    "............",
  ],
  terminal: [
    "............",
    ".##########.",
    ".#kkkkkkkk#.",
    ".#kgkkkkkk#.",
    ".#kkgkkkkk#.",
    ".#kgkyyykk#.",
    ".#kkkkkkkk#.",
    ".##########.",
    "...######...",
    "..########..",
    "............",
    "............",
  ],
  jukebox: [
    "............",
    ".##########.",
    ".#pppppppp#.",
    ".#p######p#.",
    ".#p#yyyy#p#.",
    ".#p######p#.",
    ".#pppppppp#.",
    ".#pbgbgbgp#.",
    ".##########.",
    "............",
    "............",
    "............",
  ],
  mushroom: [
    "............",
    "....####....",
    "..##rrwr##..",
    ".#rrrrrrrr#.",
    ".#rwrrrwrr#.",
    ".##########.",
    "....#ww#....",
    "....#ww#....",
    "....####....",
    "............",
  ],
};

export function PixelIcon({ id, size = 28 }: { id: IconId | "mushroom"; size?: number }) {
  const map = maps[id];
  return (
    <svg width={size} height={size} viewBox={`0 0 ${map[0].length} ${map.length}`} shapeRendering="crispEdges" style={{ imageRendering: "pixelated" }} aria-hidden="true" focusable="false">
      {map.flatMap((row, y) =>
        [...row].map((c, x) => (c === "." ? null : <rect key={`${x}-${y}`} x={x} y={y} width="1" height="1" fill={palette[c] ?? "#000"} />)),
      )}
    </svg>
  );
}
