export const os = {
  name: "PiyushOS 95",
  shortName: "PiyushOS95",
  subtitle: "realm 09 // BUILD & PHILOSOPHY",
  title: "BUILD & PHILOSOPHY",
  prompt: "C:\\PIYUSH>",
  version: "PiyushOS 95 [Version 1.0.0-sprout]",
};

export type WinId = "frontend" | "backend" | "devops" | "toolbox" | "manifesto" | "me" | "terminal" | "jukebox";

export type WinDef = {
  id: WinId;
  title: string;
  icon: IconId;
  label: string; // desktop icon label
  left: string;
  top: string;
  width: string;
  cursor?: string;
  defaultOpen?: boolean;
  aliases: string[];
  dirLine: string;
};

export type IconId = "frontend" | "backend" | "devops" | "satchel" | "scroll" | "me" | "terminal" | "jukebox";

export const windows: WinDef[] = [
  { id: "frontend", title: "frontend.sys", icon: "frontend", label: "frontend.sys", left: "14%", top: "40%", width: "340px", aliases: ["frontend", "frontend.sys", "ui"], dirLine: "48,160  frontend.sys   renders at 60fps" },
  { id: "backend", title: "backend.exe — Request Lab", icon: "backend", label: "backend.exe", left: "60%", top: "6%", width: "360px", aliases: ["backend", "backend.exe", "api"], dirLine: "31,337  backend.exe    200 OK, always" },
  { id: "devops", title: "devops.exe — Pipeline", icon: "devops", label: "devops.exe", left: "14%", top: "70%", width: "340px", aliases: ["devops", "devops.exe", "deploy"], dirLine: "27,004  devops.exe     ships on friday (brave)" },
  { id: "toolbox", title: "satchel.zip — Portal Atlas", icon: "satchel", label: "satchel.zip", left: "clamp(112px, 13%, calc(100% - 536px))", top: "4%", width: "520px", defaultOpen: true, aliases: ["satchel", "satchel.zip", "toolbox", "socials"], dirLine: "04,096  satchel.zip    4 portals, all safe" },
  { id: "manifesto", title: "manifesto.txt — Notepad", icon: "scroll", label: "manifesto.txt", left: "58%", top: "46%", width: "360px", aliases: ["manifesto", "manifesto.txt", "scroll", "scroll.txt", "philosophy"], dirLine: "01,337  manifesto.txt  5 principles" },
  { id: "me", title: "me.bmp — Paint", icon: "me", label: "me.bmp", left: "78%", top: "30%", width: "200px", cursor: "retro", defaultOpen: true, aliases: ["me", "me.bmp", "portrait", "paint"], dirLine: "262,144 me.bmp         1-bit, hand-dithered" },
  { id: "terminal", title: "C:\\PIYUSH\\terminal.exe", icon: "terminal", label: "terminal.exe", left: "40%", top: "64%", width: "380px", cursor: "retro-text", defaultOpen: true, aliases: ["terminal", "terminal.exe", "cmd"], dirLine: "09,999  terminal.exe   you are here" },
  { id: "jukebox", title: "jukebox.exe — Grove Player", icon: "jukebox", label: "jukebox.exe", left: "36%", top: "16%", width: "300px", cursor: "retro", aliases: ["jukebox", "jukebox.exe", "music", "player", "radio"], dirLine: "11,264  jukebox.exe    3 original loops" },
];

// {{TODO}} Draft principles. Rewrite in Piyush's own words.
export const manifesto = {
  header: "// manifesto, v1.0 — {{TODO}} last saved",
  principles: [
    "Ship the thing, then sharpen it.",
    "Motion is communication, not decoration.",
    "Performance is a feature.",
    "The last 4% of polish creates 90% of the feeling.",
    "Play is serious work.",
  ],
};

// Generated by scripts/gen-music.mjs (original, loopable, no licensing). Drop more files in /public/music and list them here.
export const tracks: { title: string; src: string; length: string }[] = [
  { title: "Grove Morning", src: "/music/grove-morning.wav", length: "0:44" },
  { title: "Mushroom Hour", src: "/music/mushroom-hour.wav", length: "0:44" },
  { title: "Fireflies Loop", src: "/music/fireflies-loop.wav", length: "0:44" },
];

export const portalBlurbs: Record<string, string> = {
  github: "Projects, experiments and the code behind this site.",
  linkedin: "Experience at ISRO-NRSC and FIEN Foundation, plus my full CV.",
  instagram: "Life outside the terminal.",
  email: "The direct line. Best for projects, internships and collaborations.",
};

export const tips = [
  "TIP: try 'help' — or open a window from the desktop.",
  "TIP: the clover on the wallpaper is clickable.",
  "TIP: 'dir' lists everything on this machine.",
  "TIP: there is a mascot. type 'hello'.",
];
